import { type InferModel, sql } from "drizzle-orm"
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core"

export const TranscriptSchema = sqliteTable("transcript", {
  id: integer("id", { mode: "number" }).primaryKey({ autoIncrement: true }),
  tocId: integer("tocId").notNull(),
  lang: text("lang", { length: 50 }).notNull(),
  fmt: text("fmt", { length: 50 }).notNull(),
  url: text("url").notNull(),
  autoGenerated: integer("autoGenerated").notNull(),
  timestamp: text("timestamp")
    .default(sql`CURRENT_TIMESTAMP`)
    .notNull(),
})
export type TranscriptSchema = InferModel<typeof TranscriptSchema>
